#!/bin/bash

remove_divert ()
{
	if dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --remove --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; if [ $EXIT -ne 0 ]; then exit $EXIT; fi
	fi
}

if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi
if [ "$1" = "configure" ]; then

	# only do this for install not upgrade
	if [ -e "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install" ]
	then
		rm -f "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install"
		systemctl disable fail2ban.service
		systemctl stop fail2ban.service
		systemctl enable fail2ban.service
	fi
	if systemctl is-enabled fail2ban.service >/dev/null; then systemctl start fail2ban.service; fi
fi
